sudo: required
dist: xenial
language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
# - "nightly"

git:
  depth: 1

cache:
  - apt: true
  - pip : true

# clang is required because there is not enought ram for gcc
compiler: gcc

addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
         #- llvm-toolchain-precise-3.9
      packages:
         - build-essential 
         - cython
         - g++-8
         - gcc-8
         #- clang-3.9
#env: CC=clang-3.9 CXX=clang-3.9
env: CC=gcc-8 CXX=g++-8 


# command to install dependencies
install:
- sudo cp .travis/disco.list /etc/apt/sources.list.d/disco.list
- sudo apt update
- sudo apt install libantlr4-runtime-dev antlr4
- pip install -r requirements.txt
- python setup.py install 

deploy:
  provider: pypi
  user: nic30
  password:
    secure: jMuoFXUX5kopaE0ezjl6NUtxAmr8SyKpRyqZQtv3TISOCCmyenqeMR3EVckEsslC5NpQOVDQHagevooo2Ysfpu6WaFll+QJgkvB7yvt3ZHNcXj9YITTpjJNmPF58jch5cjb+kFvMvPnvOnbasBtB+KRiV4tmGRXrgP0Qg7mamVnafo3Krq0OY5hAE+fK2WhFfkyZ8xdo1M794mHf9fIRcmT9c9D8cMatYjjbq724g3OJ8wlIWxDfoa012D+G2IdZOd5+aMkNMOPd504ZnUj40T39kVsgXv0kIx42Y/Wz4Om53UT2GwTBllERq4u5nDB6A4NiVTwpx4g9+r6rCjIBtX11bRgMaDCp7Jdn6KWOsKhvQtU4u2ZGUdIRCrIoJj0NInCfedKnF0FqYA4BC7HgbFCIUnpyKxR/uU0Vz7tD/jW4vP5tr4PcgQ2eTRM5eVJZ3dYoxzlFh2MzmjXA4+MamFVCRjmzDdvaBafEvYlyUUq0D2MQ2hMwjyNlcEIKW4eOi2LaVgdwJsKbDQHc66oVDQRRYu77yFW9XGhwFoTEn0km5TTVah0d9JwvqVzWo4R33FexuthR7pHQbIe7Shw6HKpV6JfbLtvYSLLBXK8UGlW7PXYQtAZN81fwZzXd+2RwCr8otJeGzNIHug0HjK4S0CYCx4HNi0qHXOl5B+DiPuw=
  on:
    tags: true
    branch: master

script: 
  - python setup.py test # the scikit-build automatically executes setup.py develop which requires access to installation dir


